### ISSUE TITLE
Meter Reading Values

### ISSUE THREAD

**Issue by Ogaday** [The-SmartH2O-project/datasets#1]
Hello! Firstly, thank you for this data set, it's very interesting. I just have a few questions about the consumption data:

* What are the units? I assume it is litres, but I would like to check.
* In the Valencia dataset, there are commas. Again, I guess these mark the "thousands" points, and are not decimal reads. Is this correct?
* How can I interpret the `meter_reading` values for `smart_meter_id` `0` from the Valencia dataset? Is it just bad data that I should ignore, or is there a way of interpreting it?

Thanks in advance.

**Comment by The-SmartH2O-project** [comment]
> What are the units? I assume it is litres, but I would like to check.

The units are cubic meters for both datasets, 
Remark: Valencia's dataset uses comma as decimal separator, but Terre di Pedemonte uses dot as decimal separator. 

> In the Valencia dataset, there are commas. Again, I guess these mark the "thousands" points, and are not decimal reads. Is this correct?

As explained above the Valencia's dataset uses comma as decimal separator, thus when you read `1,450` that means `1.45` cubic meters (1450 liters).

> How can I interpret the` meter_reading` values for `smart_meter_id 0` from the Valencia dataset? Is it just bad data that I should ignore, or is there a way of interpreting it? 

They are bad data, you can ignore `smart_meter_id 0`.
